site_name: Repo3 Documentation

nav:
    - Morbi non elit: 'dummy1.md'
    - Nulla elit sapien: 'dummy2.md'
    - Here is some new stuff: 'NEW.md'
   

theme: 
  name: material
  features:
    - navigation.tabs
    - navigation.sections
  #  - toc.integrate
    - navigation.top
    - search.suggest
  #  - content.action.edit
  #  - content.action.view
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - navigation.footer
    - toc.follow

  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: navy
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime


repo_url: https://github.com/Klarrio/documentation-repo-3/

